name: CI
on:
  push:
    branches: [ master ]
  pull_request:
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - node-version: 14
            os: ubuntu-latest
          - node-version: 14
            os: windows-latest
          - node-version: 14
            os: macOS-latest
          - node-version: 16
            os: ubuntu-latest
          - node-version: 18
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm install
      - run: npm run test:integration
        env:
          CI: true
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: 'npm i && npm run lint'
  Unit:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: 14
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm install
        env:
          SKIP_PREPARE: true
      - run: npm run test:unit
